version: '3'

services:
  web:
    build: .
    ports:
      - "6969:5000"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=dingo
        - POSTGRES_PASSWORD=baby
    volumes:
        - ./tmp/db:/var/lib/postgresql/data