version: '3'

services:
  web:
    build: .
    ports:
      - "6969:5000"
    restart: "no"
    restart: always
    restart: on-failure
    restart: unless-stopped

  db:
    image: postgres
    restart: "no"
    restart: always
    restart: on-failure
    restart: unless-stopped
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=dingo
        - POSTGRES_PASSWORD=baby
    volumes:
        - ./tmp/db:/var/lib/postgresql/data
    