"""empty message

Revision ID: 26426f14d7eb
Revises: e015658d8ff4
Create Date: 2020-04-29 22:41:44.638981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26426f14d7eb'
down_revision = 'e015658d8ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_uuid'), 'group', ['uuid'], unique=True)
    op.create_table('group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_membership_group_id'), 'group_membership', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_membership_member_id'), 'group_membership', ['member_id'], unique=False)
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_name', 'user', ['name'], unique=1)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_index(op.f('ix_group_membership_member_id'), table_name='group_membership')
    op.drop_index(op.f('ix_group_membership_group_id'), table_name='group_membership')
    op.drop_table('group_membership')
    op.drop_index(op.f('ix_group_uuid'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
