"""empty message

Revision ID: aab931e250af
Revises: d8f859f8e7eb
Create Date: 2020-05-06 17:42:43.770568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab931e250af'
down_revision = 'd8f859f8e7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('originating_user', sa.Integer(), nullable=True),
    sa.Column('target_user', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['originating_user'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['target_user'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_originating_user'), 'follow', ['originating_user'], unique=False)
    op.create_index(op.f('ix_follow_target_user'), 'follow', ['target_user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_target_user'), table_name='follow')
    op.drop_index(op.f('ix_follow_originating_user'), table_name='follow')
    op.drop_table('follow')
    # ### end Alembic commands ###
