"""empty message

Revision ID: d8f859f8e7eb
Revises: 26426f14d7eb
Create Date: 2020-05-06 17:42:23.821201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f859f8e7eb'
down_revision = '26426f14d7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('originating_user', sa.INTEGER(), nullable=True),
    sa.Column('target_user', sa.INTEGER(), nullable=True),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['originating_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
